export const COUNTRY_CODES = [
  // América del Norte
  { code: '1', name: 'Estados Unidos' },
  { code: '1', name: 'Canadá' },

  // Latinoamérica
  { code: '54', name: 'Argentina' },
  { code: '591', name: 'Bolivia' },
  { code: '55', name: 'Brasil' },
  { code: '56', name: 'Chile' },
  { code: '57', name: 'Colombia' },
  { code: '506', name: 'Costa Rica' },
  { code: '53', name: 'Cuba' },
  { code: '593', name: 'Ecuador' },
  { code: '503', name: 'El Salvador' },
  { code: '502', name: 'Guatemala' },
  { code: '504', name: 'Honduras' },
  { code: '52', name: 'México' },
  { code: '505', name: 'Nicaragua' },
  { code: '507', name: 'Panamá' },
  { code: '595', name: 'Paraguay' },
  { code: '51', name: 'Perú' },
  { code: '1', name: 'Puerto Rico' },
  { code: '809', name: 'República Dominicana' },
  { code: '598', name: 'Uruguay' },
  { code: '58', name: 'Venezuela' },

  // Unión Europea
  { code: '49', name: 'Alemania' },
  { code: '43', name: 'Austria' },
  { code: '32', name: 'Bélgica' },
  { code: '359', name: 'Bulgaria' },
  { code: '357', name: 'Chipre' },
  { code: '385', name: 'Croacia' },
  { code: '45', name: 'Dinamarca' },
  { code: '421', name: 'Eslovaquia' },
  { code: '386', name: 'Eslovenia' },
  { code: '34', name: 'España' },
  { code: '372', name: 'Estonia' },
  { code: '358', name: 'Finlandia' },
  { code: '33', name: 'Francia' },
  { code: '30', name: 'Grecia' },
  { code: '36', name: 'Hungría' },
  { code: '353', name: 'Irlanda' },
  { code: '39', name: 'Italia' },
  { code: '371', name: 'Letonia' },
  { code: '370', name: 'Lituania' },
  { code: '352', name: 'Luxemburgo' },
  { code: '356', name: 'Malta' },
  { code: '31', name: 'Países Bajos' },
  { code: '48', name: 'Polonia' },
  { code: '351', name: 'Portugal' },
  { code: '420', name: 'República Checa' },
  { code: '40', name: 'Rumanía' },
  { code: '46', name: 'Suecia' }
];   
